version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "9000:9000"
    volumes:
      - ./examples/clickhouse_init.d:/docker-entrypoint-initdb.d
    depends_on:
      - kafka
  exporter:
    build: .
    volumes:
      - ./:/app
    environment:
      KAFKA_URL: kafka:9092
      ZOOKEEPER_URL: zookeeper:2181
      ETHEREUM_NODE_URL: http://parity:8545
      KAFKA_TOPIC: eth_exporter_events
      START_BLOCK: 7700000
    command: ["./wait-for-it.sh", "kafka:9092", "--", "npm", "start"]
    depends_on:
      - kafka
